persistence:
  size: 1Gi

# Use the initContainer to change permissions for us so Mongo can write to the volume
volumePermissions.enabled: true

# Use the storageClass we created earlier
global:
  storageClass: tyk-mongo-pv

service:

 type: ClusterIP
 port: 27017
 portName: mongodb
